on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

name: main
jobs:
  wasm-x86:
    name: 'WASM (x86)'
    container:
      image: emscripten/emsdk:4.0.7
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install build tools
      run: ./install.build-tools.sh
      working-directory: build/wasm-x86

    - name: Update ImageMagick.commit to latest commit
      run: ./update.imagemagick.sh
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      working-directory: src/ImageMagick

    - name: Clone ImageMagick libraries
      run: ./checkout.sh wasm ../../artifacts
      working-directory: src/ImageMagick

    - name: Build dependencies
      run: ../../../../build/shared/build.dependencies.sh ../../../../build/dependencies wasm x86
      working-directory: src/ImageMagick/imagemagick-windows/Dependencies

    - name: Build ImageMagick
      run: ../../../../build/shared/build.imagemagick.sh wasm x86
      working-directory: src/ImageMagick/imagemagick-windows/ImageMagick

    - name: Build Native
      run: ../../build/shared/build.native.sh wasm x86
      working-directory: src/Magick.Native

    - name: Create wasm files
      run: npm install && npm run publish
      working-directory: src/wasm-file-creator

    - name: Copy Native
      run: ../../build/wasm-x86/copy.native.sh ../../artifacts
      working-directory: src/Magick.Native

    - name: Upload library
      uses: actions/upload-artifact@v4
      with:
        name: wasm-x86
        path: artifacts
